[[pages]]
path = "main.py"
name = "Statbomb Data Visualizations"
icon = "ğŸ’¹"

[[pages]]
path = "main_1.py"
name = "Wyscout Data Visualizations"
icon = "ğŸ“Š"

[[pages]]
path = "data/view_data.py"
name = "View Data"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "data/upload_data.py"
name = "Upload Data"
icon = "ğŸ“‹"

[[pages]]
path = "bristol_rovers_benchmark.py"
name = "Player Benchmark"
icon = "ğŸ§"
