[[pages]]
path = "main.py"
name = "Statbomb Data Visualizations"
icon = "ğŸ’¹"

[[pages]]
path = "main_1.py"
name = "Wyscout Data Visualizations"
icon = "ğŸ’¹"

[[pages]]
path = "data/view_data.py"
name = "View Data"
icon = "ğŸ“Š"
