[[pages]]
path = "main.py"
name = "Statbomb Data Visualizations"
icon = "ğŸ’¹"

[[pages]]
path = "main_1.py"
name = "Wyscout Data Visualizations"
icon = "ğŸ“Š"

[[pages]]
path = "data/view_data.py"
name = "View Data"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "data/upload_data.py"
name = "Upload Data"
icon = "ğŸ“‹"

[[pages]]
path = "Zscore_statsbomb"
name = "Zscore_statsbomb"
icon = "ğŸ“Š"

[[pages]]
path = "Zscore_Wyscout1"
name = "Zscore_Wyscout"
icon = "ğŸ“Š"

[[pages]]
path = "u19_minutes_leaders_streamlit_v2"
name = "u19_minutes_leaders"
icon = "ğŸ“Š"

[[pages]]
path = "latest_mins_script"
name = "latest_mins_script"
icon = "ğŸ“Š"
